# Generated by Django 6.0.1 on 2026-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Scent',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='oms_app.payment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('1', '1'), ('500', '500')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='oms_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='oms_app.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='oms_app.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('Liter', 'Liter'), ('Kilo', 'Kilo'), ('Gallon', 'Gallon')], max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='Product Category',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='scent',
            field=models.ForeignKey(blank=True, db_column='scent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='oms_app.scent'),
        ),
    ]
