# Generated by Django 6.0.1 on 2026-01-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0002_scent_delete_user_remove_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
