# Generated by Django 6.0.1 on 2026-02-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0003_remove_productcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='utang_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='utang_duration',
            field=models.CharField(blank=True, choices=[('7D', '7 days'), ('1M', '1 month')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Gcash', 'Gcash'), ('Utang', 'Utang')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
