# Generated by Django 6.0.1 on 2026-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0004_payment_utang_due_date_payment_utang_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
