# Generated by Django 6.0.1 on 2026-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0006_alter_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
