# Generated by Django 6.0.1 on 2026-02-07 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0007_productvariant_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='oms_app.productvariant'),
        ),
    ]
