# Generated by Django 6.0.1 on 2026-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0010_remove_order_payment_payment_customer_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name_norm',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
