# Generated by Django 6.0.1 on 2026-02-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0011_customer_customer_name_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='oms_app.order'),
        ),
    ]
