# Generated by Django 6.0.1 on 2026-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_app', '0012_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('Liter', 'Liter'), ('mL', 'mL'), ('Kilo', 'Kilo'), ('Gallon', 'Gallon')], max_length=255, null=True),
        ),
    ]
